apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    tekton.dev/categories: Messaging
    tekton.dev/displayName: Send message to Slack Channel
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/platforms: 'linux/amd64,linux/s390x,linux/ppc64le'
    tekton.dev/tags: messaging
  
  name: send-to-webhook-slack
 
  namespace: pipelines-tutorial
  labels:
    app.kubernetes.io/version: '0.1'
spec:
  description: |-
    These tasks post a simple message to a slack channel.
    This task uses Incoming Webhooks of slack to send the message.
  params:
    - description: secret name of the slack app webhook URL (key is url)
      name: webhook-secret
      type: string
    - default: 'Hello from tekton :smile:'
      description: plain text message
      name: message
      type: string
    - default: Tekton Bot
      description: plain text message
      name: bot-name
      type: string
    - default: ':smile:'
      description: plain text message
      name: icon-emoji
      type: string
    - default: '#19090898'
      description: plain text message
      name: git-revision
      type: string
    - default: START
      description: plain text message
      name: state
      type: string
  steps:
    - env:
        - name: URL
          valueFrom:
            secretKeyRef:
              key: url
              name: $(params.webhook-secret)
        - name: MESSAGE
          value: $(params.message)
        - name: BOTNAME
          value: $(params.bot-name)
        - name: EMOJI
          value: $(params.icon-emoji)
        - name: BLDID
          value: $(params.git-revision)
        - name: STATE
          value: $(params.state)
      image: >-
        docker.io/curlimages/curl:7.70.0@sha256:031df77a11e5edded840bc761a845eab6e3c2edee22669fb8ad6d59484b6a1c4
      name: post
      resources: {}
      script: |
        #!/usr/bin/env sh
        ls -ltra  /workspace/slack-script
        cp /workspace/slack-script/script.sh script.sh
        chmod +x script.sh
        ls -ltra
        echo $BLDID
        ./script.sh
      securityContext:
        runAsUser: 10007500
  workspaces:
    - name: slack-script
