apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  
  name: mvn
  namespace: pipelines-tutorial
  
spec:
  params:
    - default:
        - package
      description: The Maven goals to run
      name: GOALS
      type: array
  steps:
    - command:
        - ls
        - '-ltr'
        - /workspace/source
      image: busybox
      name: list-git-source
      resources: {}
    - args:
        - '-Dmaven.repo.local=$(workspaces.maven-repo.path)'
        - $(inputs.params.GOALS)
      command:
        - /usr/bin/mvn
      image: gcr.io/cloud-builders/mvn
      name: mvn
      resources: {}
      workingDir: /workspace/source
    - command:
        - ls
        - '-ltr'
        - /workspace/source/target
      image: busybox
      name: list-mvn-build-target
      resources: {}
  workspaces:
    - name: maven-repo
    - name: source
