apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: el-appdev-cicd-demo-app
  
  name: appdev-cicd-demo-app
  
  
  finalizers:
    - eventlisteners.triggers.tekton.dev
spec:
  namespaceSelector: {}
  resources:
    kubernetesResource:
      spec:
        template:
          metadata:
            creationTimestamp: null
          spec:
            containers:
              - env:
                  - name: TLS_CERT
                    valueFrom:
                      secretKeyRef:
                        key: tls.crt
                        name: el-appdev-cicd-demo-app
                  - name: TLS_KEY
                    valueFrom:
                      secretKeyRef:
                        key: tls.key
                        name: el-appdev-cicd-demo-app
                name: ''
                resources: {}
  serviceAccountName: pipeline
  triggers:
    - triggerRef: apdev-cicd-demo-trigger
