apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
 
  name: appdev-cicd-demo-app
  namespace: pipelines-tutorial

spec:
  params:
    - description: The git repository url
      name: git-repo-url
    - default: main
      description: The git revision
      name: git-revision
    - description: The name of the deployment to be created / patched
      name: git-repo-name
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: build-deploy-appdev-demo-$(tt.params.git-repo-name)-
      spec:
        params:
          - name: deployment-name
            value: appdev-cicd-demo-deployment
          - name: git-url
            value: $(tt.params.git-repo-url)
          - name: git-revision
            value: $(tt.params.git-revision)
          - name: IMAGE
            value: 'quay.io/xxxx/xxxx:cameldemo12222'
        pipelineRef:
          name: build-and-deploy-appdev-demo
        serviceAccountName: pipeline
        workspaces:
          - configMap:
              name: slack-post-script-cm
            name: slack-script
          - name: local-maven-repo
            volumeClaimTemplate:
              apiVersion: v1
              kind: PersistentVolumeClaim
              metadata:
                creationTimestamp: null
                name: local-maven-repo-appdev-cicd-demo-pvc
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1G
              status: {}
          - name: shared-workspace
            volumeClaimTemplate:
              apiVersion: v1
              kind: PersistentVolumeClaim
              metadata:
                creationTimestamp: null
                name: source-appdev-cicd-demo-pvc
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 500Mi
